JuliaGPU/oneAPI.jl

src/broadcast.jl, src/device/opencl/integer.jl, src/device/opencl/math.jl, src/device/opencl/utils.jl, src/mapreduce.jl, src/oneAPI.jl, test/runtests.jl
=> Support integer device intrinsics, and look up for broadcast/mapreduce

Manifest.toml, Project.toml
Fixes https://github.com/JuliaGPU/oneAPI.jl/issues/38
=> Bump NEO_jll to include DG1 support.

src/broadcast.jl, src/mapreduce.jl
Not needed anymore now that we have device overrides.
=> Remove zefunc.

Manifest.toml, src/device/opencl/atomic.jl, src/device/utils.jl, src/oneAPI.jl, test/device/intrinsics.jl
We'll need this to implement `gpu_malloc`.
=> Support for atomic intrinsics

test/setup.jl
=> Inspect device properties to determine test types.

test/execution.jl
Ref https://github.com/intel/intel-graphics-compiler/issues/172
=> Test that passing pointers as integers works.

lib/level-zero/error.jl, lib/level-zero/oneL0.jl, lib/level-zero/utils.jl
Addresses part of https://github.com/JuliaGPU/oneAPI.jl/issues/243#issuecomment-1312012319.
=> Retry API calls when running out of memory.

deps/src/onemkl.cpp
Added forced flush in order to avoid sycl command buffering.
=> Fix for copy failure

deps/src/onemkl.cpp, lib/mkl/wrappers.jl
No longer wait() is needed as Julia does call sycn when CPU read happens.
=> Minor cleanup

lib/mkl/libonemkl.jl, res/.gitignore, res/libsycl_prologue.jl, res/libze_prologue.jl, res/onemkl.toml
Fixes https://github.com/JuliaGPU/oneAPI.jl/issues/271
=> Fixes to autogenerated wrappers

.buildkite/pipeline.yml, lib/mkl/linalg.jl, src/device/quirks.jl
=> Add support for Julia 1.9.

lib/level-zero/oneL0.jl, src/oneAPI.jl
Fixes https://github.com/JuliaGPU/oneAPI.jl/issues/207
=> Check JLL availability during init.

src/device/quirks.jl
Fixes https://github.com/JuliaGPU/oneAPI.jl/issues/280
=> Fix number quirk.

lib/support/liboneapi_support.jl
=> Fix a typo in lib/support/liboneapi_support.jl

Manifest.toml, src/array.jl, src/pool.jl, test/array.jl
Everything was there already, this is just wiring things together.
=> Support for creating oneArrays backed by shard memory

deps/build_local.jl
=> Downgrade MKL.

deps/generate_interfaces.jl, deps/onemkl_epilogue.cpp, deps/onemkl_epilogue.h, deps/onemkl_prologue.cpp, deps/src/onemkl.cpp, deps/src/onemkl.h, lib/support/liboneapi_support.jl
=> Update the C interface to avoid conflicts between buffer and usm routines

deps/src/onemkl.cpp, deps/src/onemkl.h, lib/support/liboneapi_support.jl, test/onemkl.jl
Interface the two versions of the "batch" routines.
=> Interface more oneMKL routines

deps/onemkl_epilogue.cpp, deps/onemkl_epilogue.h
Peng forgot to update these files in #421.
=> Update onemkl_epilogue.cpp and onemkl_epilogue.h

lib/mkl/linalg.jl
Follow up for https://github.com/JuliaGPU/CUDA.jl/pull/2359
=> Make LinearAlgebra.generic_trimatmul more specific

src/device/opencl/math.jl
ported from https://github.com/JuliaGPU/Metal.jl/pull/379
fixes #447
GPUArrays test PR: https://github.com/JuliaGPU/GPUArrays.jl/pull/551
=> Avoid ReshapedArray using Int128 in kernel

Project.toml
Fixes https://github.com/JuliaGPU/oneAPI.jl/issues/425
=> Bump oneAPI support library.

lib/mkl/wrappers_lapack.jl, test/onemkl.jl
I did an error in CUDA.jl we now have the same one here and in AMDGPU.jl.
=> [oneMKL] Fix gesvd!

Project.toml
=> Upgrade oneAPI_Support_jll.jl

Project.toml
Release with NEO v25.31.34666. Updating NEO -> bump minor version?
=> Release 2.2.0

src/context.jl
Trying to be consistent with synchronization
=> In order global queue
