JuliaGPU/oneAPI.jl

Manifest.toml, lib/level-zero/memory.jl, lib/level-zero/residency.jl, src/array.jl, src/oneAPI.jl, src/pool.jl, test/runtests.jl
By bumping GPUArrays, materializing ReshapedArray before sending to the device.
=> Avoid Int128 operations

src/device/opencl/memory.jl
We return a LLVMPtr, so no need to ptrtoint, but we only need to get rid
of the type (Julia passes LLVMPtr as i8).
=> Fix bug in local memory.

.buildkite/pipeline.yml, Project.toml
We aren't compatible with the latest NEO, see the failures in https://github.com/JuliaGPU/oneAPI.jl/pull/52, so let's tighten compatibility.
=> Add Compat bound for NEO_jll.

Manifest.toml
This version is now (temporarily) based on https://github.com/maleadt/SPIRV-LLVM-Translator, which includes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/855/ on the LLVM 11 branch. This is needed to get `cor` working in https://github.com/JuliaGPU/CUDA.jl/pull/888.
=> Update the LLVM to SPIRV translator.

Project.toml, lib/level-zero/libze.jl, res/Manifest.toml, res/Project.toml, res/wrap.jl
Switch Clang.jl's version in Manifest.toml to master and use `get_default_args` to setup default compiler flags which is more stable.
=> Add the result of `get_default_args` as default compiler flags

lib/level-zero/libze.jl, res/Manifest.toml, res/Project.toml, res/wrap.jl, res/wrap.toml
As this package only works on Julia-1.6+, it's ok to use `@ccall` without worrying about compatibility.
=> Simplify wrap.jl by generating `@ccall` and using JuliaFormatter 

lib/level-zero/module.jl
A tiny typo in suggest_groupsize gave some very strange group sizes. 
Here is a small fix.
=> Fix typo in suggest_groupsize

lib/level-zero/memory.jl, src/pool.jl
Should fix https://github.com/JuliaGPU/oneAPI.jl/issues/113
=> Use a blocking free to avoid early memory releases.

src/device/opencl/synchronization.jl, test/execution.jl
Otherwise LLVM can reorder it in a way that the resulting control flow is invalid for a barrier.
Fixes https://github.com/JuliaGPU/oneAPI.jl/issues/160, fixes https://github.com/JuliaGPU/oneAPI.jl/issues/159
=> Ensure the barrier function is convergent.

deps/onemkl.cpp, deps/sycl.cpp, src/compiler/execution.jl
I made a few small changes to bring the tb/onemkl branch to the latest SYCL API changes.  It builds successfully but the call to MKL gemm still aborts at runtime. It will be good to get the changes in so we can debug the MKL problem with the latest SYCL compiler and MKL.  Please review.
=> Update tb/onemkl to the latest SYCL API

test/setup.jl
Closes https://github.com/JuliaGPU/oneAPI.jl/issues/108.
=> Re-enable tests for Int16/Float16.

src/compiler/execution.jl
This avoids leaking temporary variables, e.g. when working in the REPL.
=> Wrap at-oneapi's output in a let block.

deps/src/onemkl.cpp, deps/src/onemkl.h, lib/mkl/libonemkl.jl, lib/mkl/linalg.jl, lib/mkl/oneMKL.jl, lib/mkl/wrappers.jl, test/onemkl.jl
Following primitives are supported in level-3
Symmetric: symm, syrk, syr2k
Triangular: trmm, trsm
Hermitian: hemm, herk, her2k
=> Support level 3 primitives

src/mapreduce.jl
ref https://github.com/JuliaGPU/CUDA.jl/pull/1223
=> Use broadcast instead of copies to initialize mapreduce buffers.

src/random.jl, test/random.jl
=> Add GPUArrays out-of-place random methods

Manifest.toml, lib/mkl/linalg.jl
Cf. https://github.com/JuliaGPU/GPUArrays.jl/pull/472 and https://github.com/JuliaGPU/CUDA.jl/pull/1904. Same here: if `gemm_dispatch!` is (sufficiently) internal, it might be actually removed.
=> Reduce number of `mul!` methods

.buildkite/pipeline.yml, lib/mkl/linalg.jl, lib/mkl/wrappers.jl, test/onemkl.jl
This is to make use of https://github.com/JuliaLang/julia/pull/50058. While that PR has not been merged, I'm putting this up to see whether this is working properly on older julia versions, and then we check nightly later.
=> 1.10 enablement

Project.toml, src/array.jl, src/broadcast.jl, src/compiler/execution.jl, src/oneAPI.jl, src/pool.jl, test/array.jl
Similar to https://github.com/JuliaGPU/Metal.jl/pull/273 and https://github.com/JuliaGPU/CUDA.jl/pull/2203. To test this, I added some minimal wrappers for host memory, but it isn't functional yet.
=> Preserve the buffer type when broadcasting.

src/device/opencl/memory.jl
Same as https://github.com/JuliaGPU/Metal.jl/pull/283
=> Avoid redundant pointer conversions for threadgroup memory.

deps/src/onemkl.cpp, lib/mkl/oneMKL.jl, lib/mkl/wrappers_blas.jl, lib/mkl/wrappers_lapack.jl, lib/support/liboneapi_support.jl, res/support.toml, test/onemkl.jl
@kballeda @pengtu 
I wrapped additional LAPACK routines but I have some errors during the compilation.
Do you also have this issue?
Update:  The culprit was my local Intel compiler v2023.2.0 that was used. I'm able to compile with the compile installed by Conda.
=> [oneMKL] Interface lapack routines

Project.toml, lib/mkl/array.jl, lib/mkl/interfaces.jl, lib/mkl/oneMKL.jl, lib/mkl/wrappers_sparse.jl, test/onemkl.jl
@maleadt 
Should we define `AbstractoneSparseArray` or `AbstractOneSparseArray`?
off-topic:
We have the following error when we use the artifact `oneAPI_Support_jll.jl` and not the local one:
```julia
INTEL MKL ERROR: /root/.cache/julia-buildkite-plugin/depots/
05c310bb-cd1d-4bbf-ad62-61f2372c55f0/artifacts/
dacc6471ef6945fc42d4c7881bb431b19e138ba3/lib/libmkl_avx512.so.2: 
cannot open shared object file: No such file or director
```
=> Improve the dispatch for sparse routines

deps/src/onemkl.cpp
MKL team informed us that this should work starting with 2023.1 release.  Hence, try this one again to see if it also fixes the new tear down problem.
=> Another attempt to use mkl_free_buffers

deps/Project.toml, deps/build_local.jl, deps/generate_helpers.jl, deps/generate_interfaces.jl, deps/onemkl_epilogue.cpp, deps/onemkl_epilogue.h, deps/onemkl_prologue.cpp, deps/onemkl_prologue.h, deps/src/onemkl.cpp, deps/src/onemkl.h, lib/mkl/array.jl, lib/mkl/wrappers_blas.jl, lib/mkl/wrappers_sparse.jl, lib/support/liboneapi_support.jl, res/support.toml, test/level-zero.jl, test/onemkl.jl, test/runtests.jl, test/setup.jl
close #401 
The tests are failing because of an upstream issue:
https://github.com/JuliaGPU/oneAPI.jl/pull/404#issuecomment-2026874806
If we merge this PR and update `oneAPI_Support_jll.jl`, we must bump the version number to `0.4.0`.
=> Upgrade the C interface for oneAPI 2024.1.0

deps/generate_interfaces.jl, deps/onemkl_epilogue.cpp, deps/onemkl_prologue.cpp, deps/src/onemkl.cpp
Closes https://github.com/JuliaGPU/oneAPI.jl/issues/427
=> Remove flush workaround.

lib/level-zero/driver.jl, lib/level-zero/memory.jl, lib/level-zero/module.jl, lib/level-zero/oneL0.jl, src/compiler/execution.jl, src/gpuarrays.jl, src/mapreduce.jl, src/oneAPIKernels.jl, test/level-zero.jl
=> Roll our own launch configuration

src/array.jl, test/array.jl
This is a draft of an implementation of `resize!` for `oneArray`.
It is similar to the implementations for [`CuArray`](https://github.com/JuliaGPU/CUDA.jl/commit/f900010de53812b69239d0b9dfae5cd47fe97563), [`ROCArray`](https://github.com/JuliaGPU/AMDGPU.jl/pull/333), and [`MtlArray`](https://github.com/JuliaGPU/Metal.jl/pull/279).
I don't have access to an Intel GPU so don't have any way of testing it, so the current implementation is most likely wrong. I'm hoping to get some help from someone who is capable of helping, and/or use the CI tests to guide me towards a correct implementation.
In conjunction with https://github.com/JuliaGPU/GPUArrays.jl/pull/533, this will allow `append!` to be defined for `oneArray`.
@tgymnich @maleadt
=> Define `resize!`

lib/mkl/linalg.jl
This is a companion PR to https://github.com/JuliaLang/julia/pull/52439. Basically, it avoids the construction of `MulAddMul`s and simply passes the factors `alpha` and `beta` forward.
=> Avoid constructing `MulAddMul`s on Julia v1.12+

lib/mkl/wrappers_blas.jl, lib/mkl/wrappers_lapack.jl, lib/mkl/wrappers_sparse.jl, src/array.jl
When using host or shared buffer types, there isn't a clear owner, so let's use the CUDA semantics of executing on the currently-active device. This makes it possible to properly synchronize before copying host memory, which is needed for correctness.
=> Queue operations on the current device, not the one owning the array.

src/pool.jl
Memory eviction is not queue ordered, so unsafe to perform here. But it's probably not needed as we're freeing the memory anyway. This was triggered by the recent resize implementation, which frees quickly after issueing a copy operation.
Works around https://github.com/JuliaGPU/oneAPI.jl/issues/439
=> Don't evict memory before freeing it.

deps/Project.toml, deps/build_local.jl
As expected, we don't have any modification in the headers with this minor release.
Related issue: #465
=> Use the version 2024.2.1 for CI

deps/Project.toml, deps/build_local.jl
Reverts JuliaGPU/oneAPI.jl#467. Looks like v2024.2.1 is problematic wrt. building the support library on Yggdrasil, so let's temporarily revert the change here too so that we can tag a release first.
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/9552
=> Revert "Use the version 2024.2.1 for CI"

src/mapreduce.jl
No need to launch too many threads.
=> Fix mapreduce launch configuration.

deps/CMakeLists.txt, deps/Project.toml, deps/build_local.jl, deps/generate_helpers.jl, deps/generate_interfaces.jl, deps/onemkl_prologue.cpp, deps/onemkl_prologue.h, deps/src/onemkl.cpp, deps/src/onemkl.h, deps/src/sycl.cpp
We also need to update the files `sycl.cpp` and `sycl.h`.
=> Update to oneAPI v2025.0.0

Project.toml, src/oneAPI.jl
I verified this fixes #489:
```
julia> using oneAPI
┌ Error: No oneAPI Level Zero loader found for your platform. Currently, only Linux x86 is supported.
│ If you have a local oneAPI toolchain, you can use that; refer to the documentation for more details.
└ @ oneAPI.oneL0 ~/.julia/packages/oneAPI/8uwwt/lib/level-zero/oneL0.jl:118
julia> 
```
The message is only an `@error` logging, but the session is otherwise fully functional.
CC: @vchuravy.  PR best reviewed by [ignoring whitespace changes](https://github.com/JuliaGPU/oneAPI.jl/pull/493/files?w=1).
=> Make package loadable on macOS

deps/Project.toml, deps/build_local.jl
Intel didn't added any routines in oneAPI 2025.1.0.
I checked with a local build of: https://github.com/JuliaPackaging/Yggdrasil/pull/11015
No issue to compile the `liboneapi_support.so` with the new version of the compiler, let's see if we have an issue with CI.
cc @michel2323
=> [CI] Use oneAPI 2025.1.0

src/array.jl
It seems like this was accidentally left in?
=> Remove unneedded line in `oneArray` constructor

deps/generate_interfaces.jl, deps/onemkl_prologue.cpp, deps/onemkl_prologue.h, deps/src/onemkl.cpp, deps/src/onemkl.h, lib/level-zero/libze.jl, lib/mkl/oneMKL.jl, lib/support/liboneapi_support.jl, test/onemkl.jl
#525 
@michel2323 
I didn't updated `oneAPI.versioninfo()`, can you do it after the PR?
=> Add a function oneMKL.version()

Project.toml, src/accumulate.jl, src/indexing.jl, src/oneAPI.jl, test/indexing.jl
In support of https://github.com/MadNLP/MadNLP.jl/pull/476
=> `findall` support through AcceleratedKernels.jl
